const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  COMUNITY: '/community',
  COLLECTION: '/collections',
  SIGN_IN_WITH_OAUTH: '/signin-with-oauth',
  JOBS: '/find-jobs',
  TAGS: '/tags',
  PROFILE: (id: string) => `/profile/${id}`,
  ASK_QUESTION: '/ask-a-question',
  QUESTION: (id: string) => `/questions/${id}`,
  TAG: (id: string) => `/tags/${id}`,
  MODELS: '/admin/models',
  ADD_MODEL: '/admin/models/create',
  EDIT_MODEL: (id: string) => `/admin/models/${id}/edit`,
  REFERENCES: '/admin/references',
  ADD_REFERENCE: '/admin/references/create',
  EDIT_REFERENCE: (id: string) => `/admin/references/${id}/edit`,
  USERS: '/admin/users',
  ACCOUNTS: '/admin/accounts',
  EDIT_ACCOUNT: (id: string) => `/admin/accounts/${id}/edit`,
  DEVICES: '/admin/devices',
  ADD_DEVICE: '/admin/devices/create',
  EDIT_DEVICE: (id: string) => `/admin/devices/${id}/edit`,
  ASSIGN_DEVICE: (id: string) => `/admin/devices/${id}/assign`,
  LIVE_TRACKING: (id: string) => `/admin/devices/${id}/live-tracking`,

  CLIENT_DEVICES: '/devices',
  CLIENT_EDIT_DEVICE: (id: string) => `/devices/${id}/edit`,
  CLIENT_LIVE_TRACKING: (id: string) => `/devices/${id}/live-tracking`,
  CLIENT_DAILY_REPORT: (id: string) => `/devices/${id}/daily-report`,
  CLIENT_MONTHLY_REPORT: (id: string) => `/devices/${id}/monthly-report`,
};

export default ROUTES;
